#ifndef CONFIG_H
#define CONFIG_H

#define MOTOR_RIGHT_PWM PIN_TIMER1_A
#define MOTOR_RIGHT_DIR PIN_PD6
#define MOTOR_RIGHT_FEEDBACK PIN_INT0
#define MOTOR_LEFT_PWM PIN_TIMER1_B
#define MOTOR_LEFT_DIR PIN_PD5
#define MOTOR_LEFT_FEEDBACK PIN_INT1

#define BUTTON_1_PIN PIN_PC1
#define BUTTON_2_PIN PIN_PC2
#define BUTTON_3_PIN PIN_PC3
#define LED_PIN PIN_PD4
#define ADC_PIN PIN_PC0

#define RADIO_CSN_PIN PIN_PD7
#define RADIO_CE_PIN PIN_PB0

#endif
