#!/bin/sh
cd build
name=test_oscillatory

avr-objcopy -j .text -j .data -O ihex $name.elf $name.hex
avr-size --format=avr --mcu=m328p $name.elf
avrdude -c usbtiny -p m328p -U flash:w:$name.hex:i
# avrdude -c arduino -P /dev/ttyACM0 -p m328p -U flash:w:$name.hex:i
